---
- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/{{ node_exporter_package }}
    dest: /root

- name: Unzip node Exporter
  unarchive:
    src: /root/{{ node_exporter_package }}
    dest: /root
    remote_src: yes
    creates: /usr/bin/node_exporter # Does not unzip if node.exporter binary already exists

- name: Copy node_exporter to bin
  copy:
    src: /root/{{ node_exporter_dir }}/node_exporter
    dest: /usr/bin/node_exporter

- name: Create systemd unit for node_exporter
  template:
    src: ./templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: "start_node_exporter"
